// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAye0xaqLN2VAakekaueXoh4kLFCHBE4lc',
    appId: '1:527222520341:web:76ebd326833abfd32c2c1c',
    messagingSenderId: '527222520341',
    projectId: 'eatagain-2e12b',
    authDomain: 'eatagain-2e12b.firebaseapp.com',
    storageBucket: 'eatagain-2e12b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYTn-Xt04oVAQggfiIRsjSdqy_0NSq8jk',
    appId: '1:527222520341:android:4e1eb28c2a8ed4ac2c2c1c',
    messagingSenderId: '527222520341',
    projectId: 'eatagain-2e12b',
    storageBucket: 'eatagain-2e12b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCru6mgQMD9tcgSwYuiSq1lGVrDz8swcqQ',
    appId: '1:527222520341:ios:b23306677a852a502c2c1c',
    messagingSenderId: '527222520341',
    projectId: 'eatagain-2e12b',
    storageBucket: 'eatagain-2e12b.appspot.com',
    iosClientId:
        '527222520341-1n2tbnn35uk32kcrpochfqe32684rmeh.apps.googleusercontent.com',
    iosBundleId: 'com.example.eatagain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCru6mgQMD9tcgSwYuiSq1lGVrDz8swcqQ',
    appId: '1:527222520341:ios:13c47af25a7fd2432c2c1c',
    messagingSenderId: '527222520341',
    projectId: 'eatagain-2e12b',
    storageBucket: 'eatagain-2e12b.appspot.com',
    iosClientId:
        '527222520341-vbsuoqij22a46t6r4rr9vpovm2qp5fv9.apps.googleusercontent.com',
    iosBundleId: 'com.example.eatagain.RunnerTests',
  );
}
